version: '3'

services:
  redis-stack:
    image: redis/redis-stack
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     REDIS_ARGS: --requirepass labdata


  redisinsight:
    image: redislabs/redisinsight  
    container_name: redisinsight
    hostname: redislabs
    ports:
      - "8001:8001"
    depends_on:
     - redis-stack

